kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  labels:
    app: requestProcessor
    type: local
spec:
  storageClassName: "test"
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany #Can be edited to limit access: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
  hostPath:
    path: "/mnt/data"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: requestProcessor
spec:
  storageClassName: "test"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi