apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  #Specifying a label here allows OTHER resources to find and use this deployment (e.g., a service, ingress, or pod)
  labels:
    app: requestProcessor_db
spec:
  #how many node replicas we want:
  replicas: 1
  selector:
    matchLabels:
      app: requestProcessor_db
  #template is the blueprint for the POD
  template:
    metadata:
      labels:
        app: requestProcessor_db
    spec:
      containers:
      #Only specifying one container
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres-config
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresdb
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
